USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/zte/n5/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8960
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200

TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := n5

TARGET_GLOBAL_CFLAGS += -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=neon -mfloat-abi=softfp

USE_OPENGL_RENDERER := true
TARGET_USES_ION := true
TARGET_USES_OVERLAY:= true
TARGET_USES_SF_BYPASS := true
TARGET_USES_C2D_COMPOSITION := true

BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=qcom user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3
BOARD_KERNEL_BASE := 0x80200000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000

# Recovery

TARGET_RECOVERY_INITRC := device/zte/n5/recovery/init.rc

TARGET_RECOVERY_FSTAB := device/zte/n5/recovery/recovery.fstab

BOARD_UMS_LUNFILE := "/sys/devices/platform/msm_hsusb/gadget/lun%d/file"

TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/devices/platform/msm_hsusb/gadget/lun%d/file"

BOARD_SDCARD_INTERNAL_DEVICE := /dev/block/mmcblk0p26

BOARD_HAS_LARGE_FILESYSTEM := true

TARGET_OTA_ASSERT_DEVICE := Grand-Memo,n5,N5,digger,ZTE-N5,V9815,v9815,cm_n5,CM_N5

TARGET_RECOVERY_PRE_COMMAND := "touch /cache/recovery/boot;sync;"

TW_CUSTOM_POWER_BUTTON := 116

BOARD_VOLD_EMMC_SHARES_DEV_MAJOR := true
BOARD_VOLD_MAX_PARTITIONS := 26
BOARD_USE_USB_MASS_STORAGE_SWITCH := true

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760 # 10M
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760 # 10M
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 786874368 # ~750M
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648 # 2G
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_RECOVERY_PIXEL_FORMAT := "RGB_565"
RECOVERY_GRAPHICS_USE_LINELENGTH := true
DEVICE_RESOLUTION := 720x1280

TW_INTERNAL_STORAGE_PATH := "/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "sdcard"
TW_EXTERNAL_STORAGE_PATH := "/sdcard2"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard2"

# Display
TARGET_QCOM_DISPLAY_VARIANT := caf
USE_OPENGL_RENDERER := true
TARGET_USES_ION := true
TARGET_USES_C2D_COMPOSITION := true

# Audio/media
BOARD_USES_ALSA_AUDIO:= true
BUILD_WITH_ALSA_UTILS := false
TARGET_QCOM_AUDIO_VARIANT := caf
TARGET_USES_QCOM_MM_AUDIO := true
BOARD_AUDIO_CAF_LEGACY_INPUT_BUFFERSIZE := true
BOARD_HAVE_LOW_LATENCY_AUDIO := true

BOARD_CHARGER_ENABLE_SUSPEND := true

TARGET_PREBUILT_KERNEL := device/zte/n5/kernel

BOARD_HAS_NO_SELECT_BUTTON := true
